/*

  DO NOT MODIFY THIS FILE DIRECTLY!
  See module/ipdmr_module_template.cpp

*/ 

#include <Rcpp.h>

#include "SEIRmodel.h"

template <class RcppModuleClassName>
RcppModuleClassName* invalidate_default_constructor() {
  Rcpp::stop("Default constructor is disabled for this class");
  return 0;
}
#define DISABLE_DEFAULT_CONSTRUCTOR() .factory(invalidate_default_constructor)

RCPP_MODULE(IPDMRmodule){

	using namespace Rcpp;

	using SEIRdetNNN = SEIRmodel<update_type::deterministic,-1,-1,-1,true>;
	class_<SEIRdetNNN>("SEIRdetNNN")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRdetNNN::show, "The show/print method")
	  .method("update", &SEIRdetNNN::update, "The update method")  
	  .method("run", &SEIRdetNNN::run, "The run method")  
	  .method("save", &SEIRdetNNN::save, "The save method")  
	  .method("reset", &SEIRdetNNN::reset, "The reset method")  
	    
		.property("state", &SEIRdetNNN::get_state, "Get current state")
	  .property("S", &SEIRdetNNN::get_S, &SEIRdetNNN::set_S, "Get/set current S")
	  .property("E", &SEIRdetNNN::get_E, &SEIRdetNNN::set_E, "Get/set current E")
	  .property("I", &SEIRdetNNN::get_I, &SEIRdetNNN::set_I, "Get/set current I")
	  .property("R", &SEIRdetNNN::get_R, &SEIRdetNNN::set_R, "Get/set current R")
	  .property("N", &SEIRdetNNN::get_N, "Get current N")
	  .property("beta", &SEIRdetNNN::get_beta, &SEIRdetNNN::set_beta, "Get/set current beta")
	  .property("omega", &SEIRdetNNN::get_omega, &SEIRdetNNN::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRdetNNN::get_gamma, &SEIRdetNNN::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRdetNNN::get_delta, &SEIRdetNNN::set_delta, "Get/set current delta")
	  .property("repl", &SEIRdetNNN::get_repl, &SEIRdetNNN::set_repl, "Get/set current repl")
	  .property("cull", &SEIRdetNNN::get_cull, &SEIRdetNNN::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRdetNNN::get_vacc, &SEIRdetNNN::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRdetNNN::get_time, "Get current time")
	  .property("trans_external", &SEIRdetNNN::get_trans_external, &SEIRdetNNN::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRdetNNN::get_trans_type, &SEIRdetNNN::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRdetNN0 = SEIRmodel<update_type::deterministic,-1,-1,0,true>;
	class_<SEIRdetNN0>("SEIRdetNN0")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRdetNN0::show, "The show/print method")
	  .method("update", &SEIRdetNN0::update, "The update method")  
	  .method("run", &SEIRdetNN0::run, "The run method")  
	  .method("save", &SEIRdetNN0::save, "The save method")  
	  .method("reset", &SEIRdetNN0::reset, "The reset method")  
	    
		.property("state", &SEIRdetNN0::get_state, "Get current state")
	  .property("S", &SEIRdetNN0::get_S, &SEIRdetNN0::set_S, "Get/set current S")
	  .property("E", &SEIRdetNN0::get_E, &SEIRdetNN0::set_E, "Get/set current E")
	  .property("I", &SEIRdetNN0::get_I, &SEIRdetNN0::set_I, "Get/set current I")
	  .property("R", &SEIRdetNN0::get_R, &SEIRdetNN0::set_R, "Get/set current R")
	  .property("N", &SEIRdetNN0::get_N, "Get current N")
	  .property("beta", &SEIRdetNN0::get_beta, &SEIRdetNN0::set_beta, "Get/set current beta")
	  .property("omega", &SEIRdetNN0::get_omega, &SEIRdetNN0::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRdetNN0::get_gamma, &SEIRdetNN0::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRdetNN0::get_delta, &SEIRdetNN0::set_delta, "Get/set current delta")
	  .property("repl", &SEIRdetNN0::get_repl, &SEIRdetNN0::set_repl, "Get/set current repl")
	  .property("cull", &SEIRdetNN0::get_cull, &SEIRdetNN0::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRdetNN0::get_vacc, &SEIRdetNN0::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRdetNN0::get_time, "Get current time")
	  .property("trans_external", &SEIRdetNN0::get_trans_external, &SEIRdetNN0::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRdetNN0::get_trans_type, &SEIRdetNN0::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRdetNN1 = SEIRmodel<update_type::deterministic,-1,-1,1,true>;
	class_<SEIRdetNN1>("SEIRdetNN1")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRdetNN1::show, "The show/print method")
	  .method("update", &SEIRdetNN1::update, "The update method")  
	  .method("run", &SEIRdetNN1::run, "The run method")  
	  .method("save", &SEIRdetNN1::save, "The save method")  
	  .method("reset", &SEIRdetNN1::reset, "The reset method")  
	    
		.property("state", &SEIRdetNN1::get_state, "Get current state")
	  .property("S", &SEIRdetNN1::get_S, &SEIRdetNN1::set_S, "Get/set current S")
	  .property("E", &SEIRdetNN1::get_E, &SEIRdetNN1::set_E, "Get/set current E")
	  .property("I", &SEIRdetNN1::get_I, &SEIRdetNN1::set_I, "Get/set current I")
	  .property("R", &SEIRdetNN1::get_R, &SEIRdetNN1::set_R, "Get/set current R")
	  .property("N", &SEIRdetNN1::get_N, "Get current N")
	  .property("beta", &SEIRdetNN1::get_beta, &SEIRdetNN1::set_beta, "Get/set current beta")
	  .property("omega", &SEIRdetNN1::get_omega, &SEIRdetNN1::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRdetNN1::get_gamma, &SEIRdetNN1::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRdetNN1::get_delta, &SEIRdetNN1::set_delta, "Get/set current delta")
	  .property("repl", &SEIRdetNN1::get_repl, &SEIRdetNN1::set_repl, "Get/set current repl")
	  .property("cull", &SEIRdetNN1::get_cull, &SEIRdetNN1::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRdetNN1::get_vacc, &SEIRdetNN1::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRdetNN1::get_time, "Get current time")
	  .property("trans_external", &SEIRdetNN1::get_trans_external, &SEIRdetNN1::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRdetNN1::get_trans_type, &SEIRdetNN1::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRdetN1N = SEIRmodel<update_type::deterministic,-1,1,-1,true>;
	class_<SEIRdetN1N>("SEIRdetN1N")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRdetN1N::show, "The show/print method")
	  .method("update", &SEIRdetN1N::update, "The update method")  
	  .method("run", &SEIRdetN1N::run, "The run method")  
	  .method("save", &SEIRdetN1N::save, "The save method")  
	  .method("reset", &SEIRdetN1N::reset, "The reset method")  
	    
		.property("state", &SEIRdetN1N::get_state, "Get current state")
	  .property("S", &SEIRdetN1N::get_S, &SEIRdetN1N::set_S, "Get/set current S")
	  .property("E", &SEIRdetN1N::get_E, &SEIRdetN1N::set_E, "Get/set current E")
	  .property("I", &SEIRdetN1N::get_I, &SEIRdetN1N::set_I, "Get/set current I")
	  .property("R", &SEIRdetN1N::get_R, &SEIRdetN1N::set_R, "Get/set current R")
	  .property("N", &SEIRdetN1N::get_N, "Get current N")
	  .property("beta", &SEIRdetN1N::get_beta, &SEIRdetN1N::set_beta, "Get/set current beta")
	  .property("omega", &SEIRdetN1N::get_omega, &SEIRdetN1N::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRdetN1N::get_gamma, &SEIRdetN1N::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRdetN1N::get_delta, &SEIRdetN1N::set_delta, "Get/set current delta")
	  .property("repl", &SEIRdetN1N::get_repl, &SEIRdetN1N::set_repl, "Get/set current repl")
	  .property("cull", &SEIRdetN1N::get_cull, &SEIRdetN1N::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRdetN1N::get_vacc, &SEIRdetN1N::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRdetN1N::get_time, "Get current time")
	  .property("trans_external", &SEIRdetN1N::get_trans_external, &SEIRdetN1N::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRdetN1N::get_trans_type, &SEIRdetN1N::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRdetN10 = SEIRmodel<update_type::deterministic,-1,1,0,true>;
	class_<SEIRdetN10>("SEIRdetN10")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRdetN10::show, "The show/print method")
	  .method("update", &SEIRdetN10::update, "The update method")  
	  .method("run", &SEIRdetN10::run, "The run method")  
	  .method("save", &SEIRdetN10::save, "The save method")  
	  .method("reset", &SEIRdetN10::reset, "The reset method")  
	    
		.property("state", &SEIRdetN10::get_state, "Get current state")
	  .property("S", &SEIRdetN10::get_S, &SEIRdetN10::set_S, "Get/set current S")
	  .property("E", &SEIRdetN10::get_E, &SEIRdetN10::set_E, "Get/set current E")
	  .property("I", &SEIRdetN10::get_I, &SEIRdetN10::set_I, "Get/set current I")
	  .property("R", &SEIRdetN10::get_R, &SEIRdetN10::set_R, "Get/set current R")
	  .property("N", &SEIRdetN10::get_N, "Get current N")
	  .property("beta", &SEIRdetN10::get_beta, &SEIRdetN10::set_beta, "Get/set current beta")
	  .property("omega", &SEIRdetN10::get_omega, &SEIRdetN10::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRdetN10::get_gamma, &SEIRdetN10::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRdetN10::get_delta, &SEIRdetN10::set_delta, "Get/set current delta")
	  .property("repl", &SEIRdetN10::get_repl, &SEIRdetN10::set_repl, "Get/set current repl")
	  .property("cull", &SEIRdetN10::get_cull, &SEIRdetN10::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRdetN10::get_vacc, &SEIRdetN10::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRdetN10::get_time, "Get current time")
	  .property("trans_external", &SEIRdetN10::get_trans_external, &SEIRdetN10::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRdetN10::get_trans_type, &SEIRdetN10::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRdetN11 = SEIRmodel<update_type::deterministic,-1,1,1,true>;
	class_<SEIRdetN11>("SEIRdetN11")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRdetN11::show, "The show/print method")
	  .method("update", &SEIRdetN11::update, "The update method")  
	  .method("run", &SEIRdetN11::run, "The run method")  
	  .method("save", &SEIRdetN11::save, "The save method")  
	  .method("reset", &SEIRdetN11::reset, "The reset method")  
	    
		.property("state", &SEIRdetN11::get_state, "Get current state")
	  .property("S", &SEIRdetN11::get_S, &SEIRdetN11::set_S, "Get/set current S")
	  .property("E", &SEIRdetN11::get_E, &SEIRdetN11::set_E, "Get/set current E")
	  .property("I", &SEIRdetN11::get_I, &SEIRdetN11::set_I, "Get/set current I")
	  .property("R", &SEIRdetN11::get_R, &SEIRdetN11::set_R, "Get/set current R")
	  .property("N", &SEIRdetN11::get_N, "Get current N")
	  .property("beta", &SEIRdetN11::get_beta, &SEIRdetN11::set_beta, "Get/set current beta")
	  .property("omega", &SEIRdetN11::get_omega, &SEIRdetN11::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRdetN11::get_gamma, &SEIRdetN11::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRdetN11::get_delta, &SEIRdetN11::set_delta, "Get/set current delta")
	  .property("repl", &SEIRdetN11::get_repl, &SEIRdetN11::set_repl, "Get/set current repl")
	  .property("cull", &SEIRdetN11::get_cull, &SEIRdetN11::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRdetN11::get_vacc, &SEIRdetN11::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRdetN11::get_time, "Get current time")
	  .property("trans_external", &SEIRdetN11::get_trans_external, &SEIRdetN11::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRdetN11::get_trans_type, &SEIRdetN11::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRdet0NN = SEIRmodel<update_type::deterministic,0,-1,-1,true>;
	class_<SEIRdet0NN>("SEIRdet0NN")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRdet0NN::show, "The show/print method")
	  .method("update", &SEIRdet0NN::update, "The update method")  
	  .method("run", &SEIRdet0NN::run, "The run method")  
	  .method("save", &SEIRdet0NN::save, "The save method")  
	  .method("reset", &SEIRdet0NN::reset, "The reset method")  
	    
		.property("state", &SEIRdet0NN::get_state, "Get current state")
	  .property("S", &SEIRdet0NN::get_S, &SEIRdet0NN::set_S, "Get/set current S")
	  .property("E", &SEIRdet0NN::get_E, &SEIRdet0NN::set_E, "Get/set current E")
	  .property("I", &SEIRdet0NN::get_I, &SEIRdet0NN::set_I, "Get/set current I")
	  .property("R", &SEIRdet0NN::get_R, &SEIRdet0NN::set_R, "Get/set current R")
	  .property("N", &SEIRdet0NN::get_N, "Get current N")
	  .property("beta", &SEIRdet0NN::get_beta, &SEIRdet0NN::set_beta, "Get/set current beta")
	  .property("omega", &SEIRdet0NN::get_omega, &SEIRdet0NN::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRdet0NN::get_gamma, &SEIRdet0NN::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRdet0NN::get_delta, &SEIRdet0NN::set_delta, "Get/set current delta")
	  .property("repl", &SEIRdet0NN::get_repl, &SEIRdet0NN::set_repl, "Get/set current repl")
	  .property("cull", &SEIRdet0NN::get_cull, &SEIRdet0NN::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRdet0NN::get_vacc, &SEIRdet0NN::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRdet0NN::get_time, "Get current time")
	  .property("trans_external", &SEIRdet0NN::get_trans_external, &SEIRdet0NN::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRdet0NN::get_trans_type, &SEIRdet0NN::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRdet0N0 = SEIRmodel<update_type::deterministic,0,-1,0,true>;
	class_<SEIRdet0N0>("SEIRdet0N0")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRdet0N0::show, "The show/print method")
	  .method("update", &SEIRdet0N0::update, "The update method")  
	  .method("run", &SEIRdet0N0::run, "The run method")  
	  .method("save", &SEIRdet0N0::save, "The save method")  
	  .method("reset", &SEIRdet0N0::reset, "The reset method")  
	    
		.property("state", &SEIRdet0N0::get_state, "Get current state")
	  .property("S", &SEIRdet0N0::get_S, &SEIRdet0N0::set_S, "Get/set current S")
	  .property("E", &SEIRdet0N0::get_E, &SEIRdet0N0::set_E, "Get/set current E")
	  .property("I", &SEIRdet0N0::get_I, &SEIRdet0N0::set_I, "Get/set current I")
	  .property("R", &SEIRdet0N0::get_R, &SEIRdet0N0::set_R, "Get/set current R")
	  .property("N", &SEIRdet0N0::get_N, "Get current N")
	  .property("beta", &SEIRdet0N0::get_beta, &SEIRdet0N0::set_beta, "Get/set current beta")
	  .property("omega", &SEIRdet0N0::get_omega, &SEIRdet0N0::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRdet0N0::get_gamma, &SEIRdet0N0::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRdet0N0::get_delta, &SEIRdet0N0::set_delta, "Get/set current delta")
	  .property("repl", &SEIRdet0N0::get_repl, &SEIRdet0N0::set_repl, "Get/set current repl")
	  .property("cull", &SEIRdet0N0::get_cull, &SEIRdet0N0::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRdet0N0::get_vacc, &SEIRdet0N0::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRdet0N0::get_time, "Get current time")
	  .property("trans_external", &SEIRdet0N0::get_trans_external, &SEIRdet0N0::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRdet0N0::get_trans_type, &SEIRdet0N0::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRdet0N1 = SEIRmodel<update_type::deterministic,0,-1,1,true>;
	class_<SEIRdet0N1>("SEIRdet0N1")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRdet0N1::show, "The show/print method")
	  .method("update", &SEIRdet0N1::update, "The update method")  
	  .method("run", &SEIRdet0N1::run, "The run method")  
	  .method("save", &SEIRdet0N1::save, "The save method")  
	  .method("reset", &SEIRdet0N1::reset, "The reset method")  
	    
		.property("state", &SEIRdet0N1::get_state, "Get current state")
	  .property("S", &SEIRdet0N1::get_S, &SEIRdet0N1::set_S, "Get/set current S")
	  .property("E", &SEIRdet0N1::get_E, &SEIRdet0N1::set_E, "Get/set current E")
	  .property("I", &SEIRdet0N1::get_I, &SEIRdet0N1::set_I, "Get/set current I")
	  .property("R", &SEIRdet0N1::get_R, &SEIRdet0N1::set_R, "Get/set current R")
	  .property("N", &SEIRdet0N1::get_N, "Get current N")
	  .property("beta", &SEIRdet0N1::get_beta, &SEIRdet0N1::set_beta, "Get/set current beta")
	  .property("omega", &SEIRdet0N1::get_omega, &SEIRdet0N1::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRdet0N1::get_gamma, &SEIRdet0N1::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRdet0N1::get_delta, &SEIRdet0N1::set_delta, "Get/set current delta")
	  .property("repl", &SEIRdet0N1::get_repl, &SEIRdet0N1::set_repl, "Get/set current repl")
	  .property("cull", &SEIRdet0N1::get_cull, &SEIRdet0N1::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRdet0N1::get_vacc, &SEIRdet0N1::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRdet0N1::get_time, "Get current time")
	  .property("trans_external", &SEIRdet0N1::get_trans_external, &SEIRdet0N1::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRdet0N1::get_trans_type, &SEIRdet0N1::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRdet01N = SEIRmodel<update_type::deterministic,0,1,-1,true>;
	class_<SEIRdet01N>("SEIRdet01N")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRdet01N::show, "The show/print method")
	  .method("update", &SEIRdet01N::update, "The update method")  
	  .method("run", &SEIRdet01N::run, "The run method")  
	  .method("save", &SEIRdet01N::save, "The save method")  
	  .method("reset", &SEIRdet01N::reset, "The reset method")  
	    
		.property("state", &SEIRdet01N::get_state, "Get current state")
	  .property("S", &SEIRdet01N::get_S, &SEIRdet01N::set_S, "Get/set current S")
	  .property("E", &SEIRdet01N::get_E, &SEIRdet01N::set_E, "Get/set current E")
	  .property("I", &SEIRdet01N::get_I, &SEIRdet01N::set_I, "Get/set current I")
	  .property("R", &SEIRdet01N::get_R, &SEIRdet01N::set_R, "Get/set current R")
	  .property("N", &SEIRdet01N::get_N, "Get current N")
	  .property("beta", &SEIRdet01N::get_beta, &SEIRdet01N::set_beta, "Get/set current beta")
	  .property("omega", &SEIRdet01N::get_omega, &SEIRdet01N::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRdet01N::get_gamma, &SEIRdet01N::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRdet01N::get_delta, &SEIRdet01N::set_delta, "Get/set current delta")
	  .property("repl", &SEIRdet01N::get_repl, &SEIRdet01N::set_repl, "Get/set current repl")
	  .property("cull", &SEIRdet01N::get_cull, &SEIRdet01N::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRdet01N::get_vacc, &SEIRdet01N::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRdet01N::get_time, "Get current time")
	  .property("trans_external", &SEIRdet01N::get_trans_external, &SEIRdet01N::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRdet01N::get_trans_type, &SEIRdet01N::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRdet010 = SEIRmodel<update_type::deterministic,0,1,0,true>;
	class_<SEIRdet010>("SEIRdet010")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRdet010::show, "The show/print method")
	  .method("update", &SEIRdet010::update, "The update method")  
	  .method("run", &SEIRdet010::run, "The run method")  
	  .method("save", &SEIRdet010::save, "The save method")  
	  .method("reset", &SEIRdet010::reset, "The reset method")  
	    
		.property("state", &SEIRdet010::get_state, "Get current state")
	  .property("S", &SEIRdet010::get_S, &SEIRdet010::set_S, "Get/set current S")
	  .property("E", &SEIRdet010::get_E, &SEIRdet010::set_E, "Get/set current E")
	  .property("I", &SEIRdet010::get_I, &SEIRdet010::set_I, "Get/set current I")
	  .property("R", &SEIRdet010::get_R, &SEIRdet010::set_R, "Get/set current R")
	  .property("N", &SEIRdet010::get_N, "Get current N")
	  .property("beta", &SEIRdet010::get_beta, &SEIRdet010::set_beta, "Get/set current beta")
	  .property("omega", &SEIRdet010::get_omega, &SEIRdet010::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRdet010::get_gamma, &SEIRdet010::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRdet010::get_delta, &SEIRdet010::set_delta, "Get/set current delta")
	  .property("repl", &SEIRdet010::get_repl, &SEIRdet010::set_repl, "Get/set current repl")
	  .property("cull", &SEIRdet010::get_cull, &SEIRdet010::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRdet010::get_vacc, &SEIRdet010::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRdet010::get_time, "Get current time")
	  .property("trans_external", &SEIRdet010::get_trans_external, &SEIRdet010::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRdet010::get_trans_type, &SEIRdet010::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRdet011 = SEIRmodel<update_type::deterministic,0,1,1,true>;
	class_<SEIRdet011>("SEIRdet011")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRdet011::show, "The show/print method")
	  .method("update", &SEIRdet011::update, "The update method")  
	  .method("run", &SEIRdet011::run, "The run method")  
	  .method("save", &SEIRdet011::save, "The save method")  
	  .method("reset", &SEIRdet011::reset, "The reset method")  
	    
		.property("state", &SEIRdet011::get_state, "Get current state")
	  .property("S", &SEIRdet011::get_S, &SEIRdet011::set_S, "Get/set current S")
	  .property("E", &SEIRdet011::get_E, &SEIRdet011::set_E, "Get/set current E")
	  .property("I", &SEIRdet011::get_I, &SEIRdet011::set_I, "Get/set current I")
	  .property("R", &SEIRdet011::get_R, &SEIRdet011::set_R, "Get/set current R")
	  .property("N", &SEIRdet011::get_N, "Get current N")
	  .property("beta", &SEIRdet011::get_beta, &SEIRdet011::set_beta, "Get/set current beta")
	  .property("omega", &SEIRdet011::get_omega, &SEIRdet011::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRdet011::get_gamma, &SEIRdet011::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRdet011::get_delta, &SEIRdet011::set_delta, "Get/set current delta")
	  .property("repl", &SEIRdet011::get_repl, &SEIRdet011::set_repl, "Get/set current repl")
	  .property("cull", &SEIRdet011::get_cull, &SEIRdet011::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRdet011::get_vacc, &SEIRdet011::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRdet011::get_time, "Get current time")
	  .property("trans_external", &SEIRdet011::get_trans_external, &SEIRdet011::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRdet011::get_trans_type, &SEIRdet011::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRdet1NN = SEIRmodel<update_type::deterministic,1,-1,-1,true>;
	class_<SEIRdet1NN>("SEIRdet1NN")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRdet1NN::show, "The show/print method")
	  .method("update", &SEIRdet1NN::update, "The update method")  
	  .method("run", &SEIRdet1NN::run, "The run method")  
	  .method("save", &SEIRdet1NN::save, "The save method")  
	  .method("reset", &SEIRdet1NN::reset, "The reset method")  
	    
		.property("state", &SEIRdet1NN::get_state, "Get current state")
	  .property("S", &SEIRdet1NN::get_S, &SEIRdet1NN::set_S, "Get/set current S")
	  .property("E", &SEIRdet1NN::get_E, &SEIRdet1NN::set_E, "Get/set current E")
	  .property("I", &SEIRdet1NN::get_I, &SEIRdet1NN::set_I, "Get/set current I")
	  .property("R", &SEIRdet1NN::get_R, &SEIRdet1NN::set_R, "Get/set current R")
	  .property("N", &SEIRdet1NN::get_N, "Get current N")
	  .property("beta", &SEIRdet1NN::get_beta, &SEIRdet1NN::set_beta, "Get/set current beta")
	  .property("omega", &SEIRdet1NN::get_omega, &SEIRdet1NN::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRdet1NN::get_gamma, &SEIRdet1NN::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRdet1NN::get_delta, &SEIRdet1NN::set_delta, "Get/set current delta")
	  .property("repl", &SEIRdet1NN::get_repl, &SEIRdet1NN::set_repl, "Get/set current repl")
	  .property("cull", &SEIRdet1NN::get_cull, &SEIRdet1NN::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRdet1NN::get_vacc, &SEIRdet1NN::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRdet1NN::get_time, "Get current time")
	  .property("trans_external", &SEIRdet1NN::get_trans_external, &SEIRdet1NN::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRdet1NN::get_trans_type, &SEIRdet1NN::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRdet1N0 = SEIRmodel<update_type::deterministic,1,-1,0,true>;
	class_<SEIRdet1N0>("SEIRdet1N0")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRdet1N0::show, "The show/print method")
	  .method("update", &SEIRdet1N0::update, "The update method")  
	  .method("run", &SEIRdet1N0::run, "The run method")  
	  .method("save", &SEIRdet1N0::save, "The save method")  
	  .method("reset", &SEIRdet1N0::reset, "The reset method")  
	    
		.property("state", &SEIRdet1N0::get_state, "Get current state")
	  .property("S", &SEIRdet1N0::get_S, &SEIRdet1N0::set_S, "Get/set current S")
	  .property("E", &SEIRdet1N0::get_E, &SEIRdet1N0::set_E, "Get/set current E")
	  .property("I", &SEIRdet1N0::get_I, &SEIRdet1N0::set_I, "Get/set current I")
	  .property("R", &SEIRdet1N0::get_R, &SEIRdet1N0::set_R, "Get/set current R")
	  .property("N", &SEIRdet1N0::get_N, "Get current N")
	  .property("beta", &SEIRdet1N0::get_beta, &SEIRdet1N0::set_beta, "Get/set current beta")
	  .property("omega", &SEIRdet1N0::get_omega, &SEIRdet1N0::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRdet1N0::get_gamma, &SEIRdet1N0::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRdet1N0::get_delta, &SEIRdet1N0::set_delta, "Get/set current delta")
	  .property("repl", &SEIRdet1N0::get_repl, &SEIRdet1N0::set_repl, "Get/set current repl")
	  .property("cull", &SEIRdet1N0::get_cull, &SEIRdet1N0::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRdet1N0::get_vacc, &SEIRdet1N0::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRdet1N0::get_time, "Get current time")
	  .property("trans_external", &SEIRdet1N0::get_trans_external, &SEIRdet1N0::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRdet1N0::get_trans_type, &SEIRdet1N0::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRdet1N1 = SEIRmodel<update_type::deterministic,1,-1,1,true>;
	class_<SEIRdet1N1>("SEIRdet1N1")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRdet1N1::show, "The show/print method")
	  .method("update", &SEIRdet1N1::update, "The update method")  
	  .method("run", &SEIRdet1N1::run, "The run method")  
	  .method("save", &SEIRdet1N1::save, "The save method")  
	  .method("reset", &SEIRdet1N1::reset, "The reset method")  
	    
		.property("state", &SEIRdet1N1::get_state, "Get current state")
	  .property("S", &SEIRdet1N1::get_S, &SEIRdet1N1::set_S, "Get/set current S")
	  .property("E", &SEIRdet1N1::get_E, &SEIRdet1N1::set_E, "Get/set current E")
	  .property("I", &SEIRdet1N1::get_I, &SEIRdet1N1::set_I, "Get/set current I")
	  .property("R", &SEIRdet1N1::get_R, &SEIRdet1N1::set_R, "Get/set current R")
	  .property("N", &SEIRdet1N1::get_N, "Get current N")
	  .property("beta", &SEIRdet1N1::get_beta, &SEIRdet1N1::set_beta, "Get/set current beta")
	  .property("omega", &SEIRdet1N1::get_omega, &SEIRdet1N1::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRdet1N1::get_gamma, &SEIRdet1N1::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRdet1N1::get_delta, &SEIRdet1N1::set_delta, "Get/set current delta")
	  .property("repl", &SEIRdet1N1::get_repl, &SEIRdet1N1::set_repl, "Get/set current repl")
	  .property("cull", &SEIRdet1N1::get_cull, &SEIRdet1N1::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRdet1N1::get_vacc, &SEIRdet1N1::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRdet1N1::get_time, "Get current time")
	  .property("trans_external", &SEIRdet1N1::get_trans_external, &SEIRdet1N1::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRdet1N1::get_trans_type, &SEIRdet1N1::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRdet11N = SEIRmodel<update_type::deterministic,1,1,-1,true>;
	class_<SEIRdet11N>("SEIRdet11N")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRdet11N::show, "The show/print method")
	  .method("update", &SEIRdet11N::update, "The update method")  
	  .method("run", &SEIRdet11N::run, "The run method")  
	  .method("save", &SEIRdet11N::save, "The save method")  
	  .method("reset", &SEIRdet11N::reset, "The reset method")  
	    
		.property("state", &SEIRdet11N::get_state, "Get current state")
	  .property("S", &SEIRdet11N::get_S, &SEIRdet11N::set_S, "Get/set current S")
	  .property("E", &SEIRdet11N::get_E, &SEIRdet11N::set_E, "Get/set current E")
	  .property("I", &SEIRdet11N::get_I, &SEIRdet11N::set_I, "Get/set current I")
	  .property("R", &SEIRdet11N::get_R, &SEIRdet11N::set_R, "Get/set current R")
	  .property("N", &SEIRdet11N::get_N, "Get current N")
	  .property("beta", &SEIRdet11N::get_beta, &SEIRdet11N::set_beta, "Get/set current beta")
	  .property("omega", &SEIRdet11N::get_omega, &SEIRdet11N::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRdet11N::get_gamma, &SEIRdet11N::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRdet11N::get_delta, &SEIRdet11N::set_delta, "Get/set current delta")
	  .property("repl", &SEIRdet11N::get_repl, &SEIRdet11N::set_repl, "Get/set current repl")
	  .property("cull", &SEIRdet11N::get_cull, &SEIRdet11N::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRdet11N::get_vacc, &SEIRdet11N::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRdet11N::get_time, "Get current time")
	  .property("trans_external", &SEIRdet11N::get_trans_external, &SEIRdet11N::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRdet11N::get_trans_type, &SEIRdet11N::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRdet110 = SEIRmodel<update_type::deterministic,1,1,0,true>;
	class_<SEIRdet110>("SEIRdet110")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRdet110::show, "The show/print method")
	  .method("update", &SEIRdet110::update, "The update method")  
	  .method("run", &SEIRdet110::run, "The run method")  
	  .method("save", &SEIRdet110::save, "The save method")  
	  .method("reset", &SEIRdet110::reset, "The reset method")  
	    
		.property("state", &SEIRdet110::get_state, "Get current state")
	  .property("S", &SEIRdet110::get_S, &SEIRdet110::set_S, "Get/set current S")
	  .property("E", &SEIRdet110::get_E, &SEIRdet110::set_E, "Get/set current E")
	  .property("I", &SEIRdet110::get_I, &SEIRdet110::set_I, "Get/set current I")
	  .property("R", &SEIRdet110::get_R, &SEIRdet110::set_R, "Get/set current R")
	  .property("N", &SEIRdet110::get_N, "Get current N")
	  .property("beta", &SEIRdet110::get_beta, &SEIRdet110::set_beta, "Get/set current beta")
	  .property("omega", &SEIRdet110::get_omega, &SEIRdet110::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRdet110::get_gamma, &SEIRdet110::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRdet110::get_delta, &SEIRdet110::set_delta, "Get/set current delta")
	  .property("repl", &SEIRdet110::get_repl, &SEIRdet110::set_repl, "Get/set current repl")
	  .property("cull", &SEIRdet110::get_cull, &SEIRdet110::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRdet110::get_vacc, &SEIRdet110::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRdet110::get_time, "Get current time")
	  .property("trans_external", &SEIRdet110::get_trans_external, &SEIRdet110::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRdet110::get_trans_type, &SEIRdet110::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRdet111 = SEIRmodel<update_type::deterministic,1,1,1,true>;
	class_<SEIRdet111>("SEIRdet111")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRdet111::show, "The show/print method")
	  .method("update", &SEIRdet111::update, "The update method")  
	  .method("run", &SEIRdet111::run, "The run method")  
	  .method("save", &SEIRdet111::save, "The save method")  
	  .method("reset", &SEIRdet111::reset, "The reset method")  
	    
		.property("state", &SEIRdet111::get_state, "Get current state")
	  .property("S", &SEIRdet111::get_S, &SEIRdet111::set_S, "Get/set current S")
	  .property("E", &SEIRdet111::get_E, &SEIRdet111::set_E, "Get/set current E")
	  .property("I", &SEIRdet111::get_I, &SEIRdet111::set_I, "Get/set current I")
	  .property("R", &SEIRdet111::get_R, &SEIRdet111::set_R, "Get/set current R")
	  .property("N", &SEIRdet111::get_N, "Get current N")
	  .property("beta", &SEIRdet111::get_beta, &SEIRdet111::set_beta, "Get/set current beta")
	  .property("omega", &SEIRdet111::get_omega, &SEIRdet111::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRdet111::get_gamma, &SEIRdet111::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRdet111::get_delta, &SEIRdet111::set_delta, "Get/set current delta")
	  .property("repl", &SEIRdet111::get_repl, &SEIRdet111::set_repl, "Get/set current repl")
	  .property("cull", &SEIRdet111::get_cull, &SEIRdet111::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRdet111::get_vacc, &SEIRdet111::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRdet111::get_time, "Get current time")
	  .property("trans_external", &SEIRdet111::get_trans_external, &SEIRdet111::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRdet111::get_trans_type, &SEIRdet111::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRdet3NN = SEIRmodel<update_type::deterministic,3,-1,-1,true>;
	class_<SEIRdet3NN>("SEIRdet3NN")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRdet3NN::show, "The show/print method")
	  .method("update", &SEIRdet3NN::update, "The update method")  
	  .method("run", &SEIRdet3NN::run, "The run method")  
	  .method("save", &SEIRdet3NN::save, "The save method")  
	  .method("reset", &SEIRdet3NN::reset, "The reset method")  
	    
		.property("state", &SEIRdet3NN::get_state, "Get current state")
	  .property("S", &SEIRdet3NN::get_S, &SEIRdet3NN::set_S, "Get/set current S")
	  .property("E", &SEIRdet3NN::get_E, &SEIRdet3NN::set_E, "Get/set current E")
	  .property("I", &SEIRdet3NN::get_I, &SEIRdet3NN::set_I, "Get/set current I")
	  .property("R", &SEIRdet3NN::get_R, &SEIRdet3NN::set_R, "Get/set current R")
	  .property("N", &SEIRdet3NN::get_N, "Get current N")
	  .property("beta", &SEIRdet3NN::get_beta, &SEIRdet3NN::set_beta, "Get/set current beta")
	  .property("omega", &SEIRdet3NN::get_omega, &SEIRdet3NN::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRdet3NN::get_gamma, &SEIRdet3NN::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRdet3NN::get_delta, &SEIRdet3NN::set_delta, "Get/set current delta")
	  .property("repl", &SEIRdet3NN::get_repl, &SEIRdet3NN::set_repl, "Get/set current repl")
	  .property("cull", &SEIRdet3NN::get_cull, &SEIRdet3NN::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRdet3NN::get_vacc, &SEIRdet3NN::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRdet3NN::get_time, "Get current time")
	  .property("trans_external", &SEIRdet3NN::get_trans_external, &SEIRdet3NN::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRdet3NN::get_trans_type, &SEIRdet3NN::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRdet3N0 = SEIRmodel<update_type::deterministic,3,-1,0,true>;
	class_<SEIRdet3N0>("SEIRdet3N0")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRdet3N0::show, "The show/print method")
	  .method("update", &SEIRdet3N0::update, "The update method")  
	  .method("run", &SEIRdet3N0::run, "The run method")  
	  .method("save", &SEIRdet3N0::save, "The save method")  
	  .method("reset", &SEIRdet3N0::reset, "The reset method")  
	    
		.property("state", &SEIRdet3N0::get_state, "Get current state")
	  .property("S", &SEIRdet3N0::get_S, &SEIRdet3N0::set_S, "Get/set current S")
	  .property("E", &SEIRdet3N0::get_E, &SEIRdet3N0::set_E, "Get/set current E")
	  .property("I", &SEIRdet3N0::get_I, &SEIRdet3N0::set_I, "Get/set current I")
	  .property("R", &SEIRdet3N0::get_R, &SEIRdet3N0::set_R, "Get/set current R")
	  .property("N", &SEIRdet3N0::get_N, "Get current N")
	  .property("beta", &SEIRdet3N0::get_beta, &SEIRdet3N0::set_beta, "Get/set current beta")
	  .property("omega", &SEIRdet3N0::get_omega, &SEIRdet3N0::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRdet3N0::get_gamma, &SEIRdet3N0::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRdet3N0::get_delta, &SEIRdet3N0::set_delta, "Get/set current delta")
	  .property("repl", &SEIRdet3N0::get_repl, &SEIRdet3N0::set_repl, "Get/set current repl")
	  .property("cull", &SEIRdet3N0::get_cull, &SEIRdet3N0::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRdet3N0::get_vacc, &SEIRdet3N0::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRdet3N0::get_time, "Get current time")
	  .property("trans_external", &SEIRdet3N0::get_trans_external, &SEIRdet3N0::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRdet3N0::get_trans_type, &SEIRdet3N0::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRdet3N1 = SEIRmodel<update_type::deterministic,3,-1,1,true>;
	class_<SEIRdet3N1>("SEIRdet3N1")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRdet3N1::show, "The show/print method")
	  .method("update", &SEIRdet3N1::update, "The update method")  
	  .method("run", &SEIRdet3N1::run, "The run method")  
	  .method("save", &SEIRdet3N1::save, "The save method")  
	  .method("reset", &SEIRdet3N1::reset, "The reset method")  
	    
		.property("state", &SEIRdet3N1::get_state, "Get current state")
	  .property("S", &SEIRdet3N1::get_S, &SEIRdet3N1::set_S, "Get/set current S")
	  .property("E", &SEIRdet3N1::get_E, &SEIRdet3N1::set_E, "Get/set current E")
	  .property("I", &SEIRdet3N1::get_I, &SEIRdet3N1::set_I, "Get/set current I")
	  .property("R", &SEIRdet3N1::get_R, &SEIRdet3N1::set_R, "Get/set current R")
	  .property("N", &SEIRdet3N1::get_N, "Get current N")
	  .property("beta", &SEIRdet3N1::get_beta, &SEIRdet3N1::set_beta, "Get/set current beta")
	  .property("omega", &SEIRdet3N1::get_omega, &SEIRdet3N1::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRdet3N1::get_gamma, &SEIRdet3N1::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRdet3N1::get_delta, &SEIRdet3N1::set_delta, "Get/set current delta")
	  .property("repl", &SEIRdet3N1::get_repl, &SEIRdet3N1::set_repl, "Get/set current repl")
	  .property("cull", &SEIRdet3N1::get_cull, &SEIRdet3N1::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRdet3N1::get_vacc, &SEIRdet3N1::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRdet3N1::get_time, "Get current time")
	  .property("trans_external", &SEIRdet3N1::get_trans_external, &SEIRdet3N1::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRdet3N1::get_trans_type, &SEIRdet3N1::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRdet31N = SEIRmodel<update_type::deterministic,3,1,-1,true>;
	class_<SEIRdet31N>("SEIRdet31N")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRdet31N::show, "The show/print method")
	  .method("update", &SEIRdet31N::update, "The update method")  
	  .method("run", &SEIRdet31N::run, "The run method")  
	  .method("save", &SEIRdet31N::save, "The save method")  
	  .method("reset", &SEIRdet31N::reset, "The reset method")  
	    
		.property("state", &SEIRdet31N::get_state, "Get current state")
	  .property("S", &SEIRdet31N::get_S, &SEIRdet31N::set_S, "Get/set current S")
	  .property("E", &SEIRdet31N::get_E, &SEIRdet31N::set_E, "Get/set current E")
	  .property("I", &SEIRdet31N::get_I, &SEIRdet31N::set_I, "Get/set current I")
	  .property("R", &SEIRdet31N::get_R, &SEIRdet31N::set_R, "Get/set current R")
	  .property("N", &SEIRdet31N::get_N, "Get current N")
	  .property("beta", &SEIRdet31N::get_beta, &SEIRdet31N::set_beta, "Get/set current beta")
	  .property("omega", &SEIRdet31N::get_omega, &SEIRdet31N::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRdet31N::get_gamma, &SEIRdet31N::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRdet31N::get_delta, &SEIRdet31N::set_delta, "Get/set current delta")
	  .property("repl", &SEIRdet31N::get_repl, &SEIRdet31N::set_repl, "Get/set current repl")
	  .property("cull", &SEIRdet31N::get_cull, &SEIRdet31N::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRdet31N::get_vacc, &SEIRdet31N::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRdet31N::get_time, "Get current time")
	  .property("trans_external", &SEIRdet31N::get_trans_external, &SEIRdet31N::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRdet31N::get_trans_type, &SEIRdet31N::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRdet310 = SEIRmodel<update_type::deterministic,3,1,0,true>;
	class_<SEIRdet310>("SEIRdet310")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRdet310::show, "The show/print method")
	  .method("update", &SEIRdet310::update, "The update method")  
	  .method("run", &SEIRdet310::run, "The run method")  
	  .method("save", &SEIRdet310::save, "The save method")  
	  .method("reset", &SEIRdet310::reset, "The reset method")  
	    
		.property("state", &SEIRdet310::get_state, "Get current state")
	  .property("S", &SEIRdet310::get_S, &SEIRdet310::set_S, "Get/set current S")
	  .property("E", &SEIRdet310::get_E, &SEIRdet310::set_E, "Get/set current E")
	  .property("I", &SEIRdet310::get_I, &SEIRdet310::set_I, "Get/set current I")
	  .property("R", &SEIRdet310::get_R, &SEIRdet310::set_R, "Get/set current R")
	  .property("N", &SEIRdet310::get_N, "Get current N")
	  .property("beta", &SEIRdet310::get_beta, &SEIRdet310::set_beta, "Get/set current beta")
	  .property("omega", &SEIRdet310::get_omega, &SEIRdet310::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRdet310::get_gamma, &SEIRdet310::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRdet310::get_delta, &SEIRdet310::set_delta, "Get/set current delta")
	  .property("repl", &SEIRdet310::get_repl, &SEIRdet310::set_repl, "Get/set current repl")
	  .property("cull", &SEIRdet310::get_cull, &SEIRdet310::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRdet310::get_vacc, &SEIRdet310::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRdet310::get_time, "Get current time")
	  .property("trans_external", &SEIRdet310::get_trans_external, &SEIRdet310::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRdet310::get_trans_type, &SEIRdet310::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRdet311 = SEIRmodel<update_type::deterministic,3,1,1,true>;
	class_<SEIRdet311>("SEIRdet311")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRdet311::show, "The show/print method")
	  .method("update", &SEIRdet311::update, "The update method")  
	  .method("run", &SEIRdet311::run, "The run method")  
	  .method("save", &SEIRdet311::save, "The save method")  
	  .method("reset", &SEIRdet311::reset, "The reset method")  
	    
		.property("state", &SEIRdet311::get_state, "Get current state")
	  .property("S", &SEIRdet311::get_S, &SEIRdet311::set_S, "Get/set current S")
	  .property("E", &SEIRdet311::get_E, &SEIRdet311::set_E, "Get/set current E")
	  .property("I", &SEIRdet311::get_I, &SEIRdet311::set_I, "Get/set current I")
	  .property("R", &SEIRdet311::get_R, &SEIRdet311::set_R, "Get/set current R")
	  .property("N", &SEIRdet311::get_N, "Get current N")
	  .property("beta", &SEIRdet311::get_beta, &SEIRdet311::set_beta, "Get/set current beta")
	  .property("omega", &SEIRdet311::get_omega, &SEIRdet311::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRdet311::get_gamma, &SEIRdet311::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRdet311::get_delta, &SEIRdet311::set_delta, "Get/set current delta")
	  .property("repl", &SEIRdet311::get_repl, &SEIRdet311::set_repl, "Get/set current repl")
	  .property("cull", &SEIRdet311::get_cull, &SEIRdet311::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRdet311::get_vacc, &SEIRdet311::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRdet311::get_time, "Get current time")
	  .property("trans_external", &SEIRdet311::get_trans_external, &SEIRdet311::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRdet311::get_trans_type, &SEIRdet311::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRstocNNN = SEIRmodel<update_type::stochastic,-1,-1,-1,true>;
	class_<SEIRstocNNN>("SEIRstocNNN")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRstocNNN::show, "The show/print method")
	  .method("update", &SEIRstocNNN::update, "The update method")  
	  .method("run", &SEIRstocNNN::run, "The run method")  
	  .method("save", &SEIRstocNNN::save, "The save method")  
	  .method("reset", &SEIRstocNNN::reset, "The reset method")  
	    
		.property("state", &SEIRstocNNN::get_state, "Get current state")
	  .property("S", &SEIRstocNNN::get_S, &SEIRstocNNN::set_S, "Get/set current S")
	  .property("E", &SEIRstocNNN::get_E, &SEIRstocNNN::set_E, "Get/set current E")
	  .property("I", &SEIRstocNNN::get_I, &SEIRstocNNN::set_I, "Get/set current I")
	  .property("R", &SEIRstocNNN::get_R, &SEIRstocNNN::set_R, "Get/set current R")
	  .property("N", &SEIRstocNNN::get_N, "Get current N")
	  .property("beta", &SEIRstocNNN::get_beta, &SEIRstocNNN::set_beta, "Get/set current beta")
	  .property("omega", &SEIRstocNNN::get_omega, &SEIRstocNNN::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRstocNNN::get_gamma, &SEIRstocNNN::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRstocNNN::get_delta, &SEIRstocNNN::set_delta, "Get/set current delta")
	  .property("repl", &SEIRstocNNN::get_repl, &SEIRstocNNN::set_repl, "Get/set current repl")
	  .property("cull", &SEIRstocNNN::get_cull, &SEIRstocNNN::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRstocNNN::get_vacc, &SEIRstocNNN::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRstocNNN::get_time, "Get current time")
	  .property("trans_external", &SEIRstocNNN::get_trans_external, &SEIRstocNNN::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRstocNNN::get_trans_type, &SEIRstocNNN::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRstocNN0 = SEIRmodel<update_type::stochastic,-1,-1,0,true>;
	class_<SEIRstocNN0>("SEIRstocNN0")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRstocNN0::show, "The show/print method")
	  .method("update", &SEIRstocNN0::update, "The update method")  
	  .method("run", &SEIRstocNN0::run, "The run method")  
	  .method("save", &SEIRstocNN0::save, "The save method")  
	  .method("reset", &SEIRstocNN0::reset, "The reset method")  
	    
		.property("state", &SEIRstocNN0::get_state, "Get current state")
	  .property("S", &SEIRstocNN0::get_S, &SEIRstocNN0::set_S, "Get/set current S")
	  .property("E", &SEIRstocNN0::get_E, &SEIRstocNN0::set_E, "Get/set current E")
	  .property("I", &SEIRstocNN0::get_I, &SEIRstocNN0::set_I, "Get/set current I")
	  .property("R", &SEIRstocNN0::get_R, &SEIRstocNN0::set_R, "Get/set current R")
	  .property("N", &SEIRstocNN0::get_N, "Get current N")
	  .property("beta", &SEIRstocNN0::get_beta, &SEIRstocNN0::set_beta, "Get/set current beta")
	  .property("omega", &SEIRstocNN0::get_omega, &SEIRstocNN0::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRstocNN0::get_gamma, &SEIRstocNN0::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRstocNN0::get_delta, &SEIRstocNN0::set_delta, "Get/set current delta")
	  .property("repl", &SEIRstocNN0::get_repl, &SEIRstocNN0::set_repl, "Get/set current repl")
	  .property("cull", &SEIRstocNN0::get_cull, &SEIRstocNN0::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRstocNN0::get_vacc, &SEIRstocNN0::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRstocNN0::get_time, "Get current time")
	  .property("trans_external", &SEIRstocNN0::get_trans_external, &SEIRstocNN0::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRstocNN0::get_trans_type, &SEIRstocNN0::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRstocNN1 = SEIRmodel<update_type::stochastic,-1,-1,1,true>;
	class_<SEIRstocNN1>("SEIRstocNN1")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRstocNN1::show, "The show/print method")
	  .method("update", &SEIRstocNN1::update, "The update method")  
	  .method("run", &SEIRstocNN1::run, "The run method")  
	  .method("save", &SEIRstocNN1::save, "The save method")  
	  .method("reset", &SEIRstocNN1::reset, "The reset method")  
	    
		.property("state", &SEIRstocNN1::get_state, "Get current state")
	  .property("S", &SEIRstocNN1::get_S, &SEIRstocNN1::set_S, "Get/set current S")
	  .property("E", &SEIRstocNN1::get_E, &SEIRstocNN1::set_E, "Get/set current E")
	  .property("I", &SEIRstocNN1::get_I, &SEIRstocNN1::set_I, "Get/set current I")
	  .property("R", &SEIRstocNN1::get_R, &SEIRstocNN1::set_R, "Get/set current R")
	  .property("N", &SEIRstocNN1::get_N, "Get current N")
	  .property("beta", &SEIRstocNN1::get_beta, &SEIRstocNN1::set_beta, "Get/set current beta")
	  .property("omega", &SEIRstocNN1::get_omega, &SEIRstocNN1::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRstocNN1::get_gamma, &SEIRstocNN1::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRstocNN1::get_delta, &SEIRstocNN1::set_delta, "Get/set current delta")
	  .property("repl", &SEIRstocNN1::get_repl, &SEIRstocNN1::set_repl, "Get/set current repl")
	  .property("cull", &SEIRstocNN1::get_cull, &SEIRstocNN1::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRstocNN1::get_vacc, &SEIRstocNN1::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRstocNN1::get_time, "Get current time")
	  .property("trans_external", &SEIRstocNN1::get_trans_external, &SEIRstocNN1::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRstocNN1::get_trans_type, &SEIRstocNN1::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRstocN1N = SEIRmodel<update_type::stochastic,-1,1,-1,true>;
	class_<SEIRstocN1N>("SEIRstocN1N")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRstocN1N::show, "The show/print method")
	  .method("update", &SEIRstocN1N::update, "The update method")  
	  .method("run", &SEIRstocN1N::run, "The run method")  
	  .method("save", &SEIRstocN1N::save, "The save method")  
	  .method("reset", &SEIRstocN1N::reset, "The reset method")  
	    
		.property("state", &SEIRstocN1N::get_state, "Get current state")
	  .property("S", &SEIRstocN1N::get_S, &SEIRstocN1N::set_S, "Get/set current S")
	  .property("E", &SEIRstocN1N::get_E, &SEIRstocN1N::set_E, "Get/set current E")
	  .property("I", &SEIRstocN1N::get_I, &SEIRstocN1N::set_I, "Get/set current I")
	  .property("R", &SEIRstocN1N::get_R, &SEIRstocN1N::set_R, "Get/set current R")
	  .property("N", &SEIRstocN1N::get_N, "Get current N")
	  .property("beta", &SEIRstocN1N::get_beta, &SEIRstocN1N::set_beta, "Get/set current beta")
	  .property("omega", &SEIRstocN1N::get_omega, &SEIRstocN1N::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRstocN1N::get_gamma, &SEIRstocN1N::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRstocN1N::get_delta, &SEIRstocN1N::set_delta, "Get/set current delta")
	  .property("repl", &SEIRstocN1N::get_repl, &SEIRstocN1N::set_repl, "Get/set current repl")
	  .property("cull", &SEIRstocN1N::get_cull, &SEIRstocN1N::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRstocN1N::get_vacc, &SEIRstocN1N::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRstocN1N::get_time, "Get current time")
	  .property("trans_external", &SEIRstocN1N::get_trans_external, &SEIRstocN1N::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRstocN1N::get_trans_type, &SEIRstocN1N::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRstocN10 = SEIRmodel<update_type::stochastic,-1,1,0,true>;
	class_<SEIRstocN10>("SEIRstocN10")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRstocN10::show, "The show/print method")
	  .method("update", &SEIRstocN10::update, "The update method")  
	  .method("run", &SEIRstocN10::run, "The run method")  
	  .method("save", &SEIRstocN10::save, "The save method")  
	  .method("reset", &SEIRstocN10::reset, "The reset method")  
	    
		.property("state", &SEIRstocN10::get_state, "Get current state")
	  .property("S", &SEIRstocN10::get_S, &SEIRstocN10::set_S, "Get/set current S")
	  .property("E", &SEIRstocN10::get_E, &SEIRstocN10::set_E, "Get/set current E")
	  .property("I", &SEIRstocN10::get_I, &SEIRstocN10::set_I, "Get/set current I")
	  .property("R", &SEIRstocN10::get_R, &SEIRstocN10::set_R, "Get/set current R")
	  .property("N", &SEIRstocN10::get_N, "Get current N")
	  .property("beta", &SEIRstocN10::get_beta, &SEIRstocN10::set_beta, "Get/set current beta")
	  .property("omega", &SEIRstocN10::get_omega, &SEIRstocN10::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRstocN10::get_gamma, &SEIRstocN10::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRstocN10::get_delta, &SEIRstocN10::set_delta, "Get/set current delta")
	  .property("repl", &SEIRstocN10::get_repl, &SEIRstocN10::set_repl, "Get/set current repl")
	  .property("cull", &SEIRstocN10::get_cull, &SEIRstocN10::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRstocN10::get_vacc, &SEIRstocN10::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRstocN10::get_time, "Get current time")
	  .property("trans_external", &SEIRstocN10::get_trans_external, &SEIRstocN10::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRstocN10::get_trans_type, &SEIRstocN10::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRstocN11 = SEIRmodel<update_type::stochastic,-1,1,1,true>;
	class_<SEIRstocN11>("SEIRstocN11")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRstocN11::show, "The show/print method")
	  .method("update", &SEIRstocN11::update, "The update method")  
	  .method("run", &SEIRstocN11::run, "The run method")  
	  .method("save", &SEIRstocN11::save, "The save method")  
	  .method("reset", &SEIRstocN11::reset, "The reset method")  
	    
		.property("state", &SEIRstocN11::get_state, "Get current state")
	  .property("S", &SEIRstocN11::get_S, &SEIRstocN11::set_S, "Get/set current S")
	  .property("E", &SEIRstocN11::get_E, &SEIRstocN11::set_E, "Get/set current E")
	  .property("I", &SEIRstocN11::get_I, &SEIRstocN11::set_I, "Get/set current I")
	  .property("R", &SEIRstocN11::get_R, &SEIRstocN11::set_R, "Get/set current R")
	  .property("N", &SEIRstocN11::get_N, "Get current N")
	  .property("beta", &SEIRstocN11::get_beta, &SEIRstocN11::set_beta, "Get/set current beta")
	  .property("omega", &SEIRstocN11::get_omega, &SEIRstocN11::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRstocN11::get_gamma, &SEIRstocN11::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRstocN11::get_delta, &SEIRstocN11::set_delta, "Get/set current delta")
	  .property("repl", &SEIRstocN11::get_repl, &SEIRstocN11::set_repl, "Get/set current repl")
	  .property("cull", &SEIRstocN11::get_cull, &SEIRstocN11::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRstocN11::get_vacc, &SEIRstocN11::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRstocN11::get_time, "Get current time")
	  .property("trans_external", &SEIRstocN11::get_trans_external, &SEIRstocN11::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRstocN11::get_trans_type, &SEIRstocN11::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRstoc0NN = SEIRmodel<update_type::stochastic,0,-1,-1,true>;
	class_<SEIRstoc0NN>("SEIRstoc0NN")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRstoc0NN::show, "The show/print method")
	  .method("update", &SEIRstoc0NN::update, "The update method")  
	  .method("run", &SEIRstoc0NN::run, "The run method")  
	  .method("save", &SEIRstoc0NN::save, "The save method")  
	  .method("reset", &SEIRstoc0NN::reset, "The reset method")  
	    
		.property("state", &SEIRstoc0NN::get_state, "Get current state")
	  .property("S", &SEIRstoc0NN::get_S, &SEIRstoc0NN::set_S, "Get/set current S")
	  .property("E", &SEIRstoc0NN::get_E, &SEIRstoc0NN::set_E, "Get/set current E")
	  .property("I", &SEIRstoc0NN::get_I, &SEIRstoc0NN::set_I, "Get/set current I")
	  .property("R", &SEIRstoc0NN::get_R, &SEIRstoc0NN::set_R, "Get/set current R")
	  .property("N", &SEIRstoc0NN::get_N, "Get current N")
	  .property("beta", &SEIRstoc0NN::get_beta, &SEIRstoc0NN::set_beta, "Get/set current beta")
	  .property("omega", &SEIRstoc0NN::get_omega, &SEIRstoc0NN::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRstoc0NN::get_gamma, &SEIRstoc0NN::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRstoc0NN::get_delta, &SEIRstoc0NN::set_delta, "Get/set current delta")
	  .property("repl", &SEIRstoc0NN::get_repl, &SEIRstoc0NN::set_repl, "Get/set current repl")
	  .property("cull", &SEIRstoc0NN::get_cull, &SEIRstoc0NN::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRstoc0NN::get_vacc, &SEIRstoc0NN::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRstoc0NN::get_time, "Get current time")
	  .property("trans_external", &SEIRstoc0NN::get_trans_external, &SEIRstoc0NN::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRstoc0NN::get_trans_type, &SEIRstoc0NN::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRstoc0N0 = SEIRmodel<update_type::stochastic,0,-1,0,true>;
	class_<SEIRstoc0N0>("SEIRstoc0N0")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRstoc0N0::show, "The show/print method")
	  .method("update", &SEIRstoc0N0::update, "The update method")  
	  .method("run", &SEIRstoc0N0::run, "The run method")  
	  .method("save", &SEIRstoc0N0::save, "The save method")  
	  .method("reset", &SEIRstoc0N0::reset, "The reset method")  
	    
		.property("state", &SEIRstoc0N0::get_state, "Get current state")
	  .property("S", &SEIRstoc0N0::get_S, &SEIRstoc0N0::set_S, "Get/set current S")
	  .property("E", &SEIRstoc0N0::get_E, &SEIRstoc0N0::set_E, "Get/set current E")
	  .property("I", &SEIRstoc0N0::get_I, &SEIRstoc0N0::set_I, "Get/set current I")
	  .property("R", &SEIRstoc0N0::get_R, &SEIRstoc0N0::set_R, "Get/set current R")
	  .property("N", &SEIRstoc0N0::get_N, "Get current N")
	  .property("beta", &SEIRstoc0N0::get_beta, &SEIRstoc0N0::set_beta, "Get/set current beta")
	  .property("omega", &SEIRstoc0N0::get_omega, &SEIRstoc0N0::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRstoc0N0::get_gamma, &SEIRstoc0N0::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRstoc0N0::get_delta, &SEIRstoc0N0::set_delta, "Get/set current delta")
	  .property("repl", &SEIRstoc0N0::get_repl, &SEIRstoc0N0::set_repl, "Get/set current repl")
	  .property("cull", &SEIRstoc0N0::get_cull, &SEIRstoc0N0::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRstoc0N0::get_vacc, &SEIRstoc0N0::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRstoc0N0::get_time, "Get current time")
	  .property("trans_external", &SEIRstoc0N0::get_trans_external, &SEIRstoc0N0::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRstoc0N0::get_trans_type, &SEIRstoc0N0::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRstoc0N1 = SEIRmodel<update_type::stochastic,0,-1,1,true>;
	class_<SEIRstoc0N1>("SEIRstoc0N1")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRstoc0N1::show, "The show/print method")
	  .method("update", &SEIRstoc0N1::update, "The update method")  
	  .method("run", &SEIRstoc0N1::run, "The run method")  
	  .method("save", &SEIRstoc0N1::save, "The save method")  
	  .method("reset", &SEIRstoc0N1::reset, "The reset method")  
	    
		.property("state", &SEIRstoc0N1::get_state, "Get current state")
	  .property("S", &SEIRstoc0N1::get_S, &SEIRstoc0N1::set_S, "Get/set current S")
	  .property("E", &SEIRstoc0N1::get_E, &SEIRstoc0N1::set_E, "Get/set current E")
	  .property("I", &SEIRstoc0N1::get_I, &SEIRstoc0N1::set_I, "Get/set current I")
	  .property("R", &SEIRstoc0N1::get_R, &SEIRstoc0N1::set_R, "Get/set current R")
	  .property("N", &SEIRstoc0N1::get_N, "Get current N")
	  .property("beta", &SEIRstoc0N1::get_beta, &SEIRstoc0N1::set_beta, "Get/set current beta")
	  .property("omega", &SEIRstoc0N1::get_omega, &SEIRstoc0N1::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRstoc0N1::get_gamma, &SEIRstoc0N1::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRstoc0N1::get_delta, &SEIRstoc0N1::set_delta, "Get/set current delta")
	  .property("repl", &SEIRstoc0N1::get_repl, &SEIRstoc0N1::set_repl, "Get/set current repl")
	  .property("cull", &SEIRstoc0N1::get_cull, &SEIRstoc0N1::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRstoc0N1::get_vacc, &SEIRstoc0N1::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRstoc0N1::get_time, "Get current time")
	  .property("trans_external", &SEIRstoc0N1::get_trans_external, &SEIRstoc0N1::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRstoc0N1::get_trans_type, &SEIRstoc0N1::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRstoc01N = SEIRmodel<update_type::stochastic,0,1,-1,true>;
	class_<SEIRstoc01N>("SEIRstoc01N")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRstoc01N::show, "The show/print method")
	  .method("update", &SEIRstoc01N::update, "The update method")  
	  .method("run", &SEIRstoc01N::run, "The run method")  
	  .method("save", &SEIRstoc01N::save, "The save method")  
	  .method("reset", &SEIRstoc01N::reset, "The reset method")  
	    
		.property("state", &SEIRstoc01N::get_state, "Get current state")
	  .property("S", &SEIRstoc01N::get_S, &SEIRstoc01N::set_S, "Get/set current S")
	  .property("E", &SEIRstoc01N::get_E, &SEIRstoc01N::set_E, "Get/set current E")
	  .property("I", &SEIRstoc01N::get_I, &SEIRstoc01N::set_I, "Get/set current I")
	  .property("R", &SEIRstoc01N::get_R, &SEIRstoc01N::set_R, "Get/set current R")
	  .property("N", &SEIRstoc01N::get_N, "Get current N")
	  .property("beta", &SEIRstoc01N::get_beta, &SEIRstoc01N::set_beta, "Get/set current beta")
	  .property("omega", &SEIRstoc01N::get_omega, &SEIRstoc01N::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRstoc01N::get_gamma, &SEIRstoc01N::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRstoc01N::get_delta, &SEIRstoc01N::set_delta, "Get/set current delta")
	  .property("repl", &SEIRstoc01N::get_repl, &SEIRstoc01N::set_repl, "Get/set current repl")
	  .property("cull", &SEIRstoc01N::get_cull, &SEIRstoc01N::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRstoc01N::get_vacc, &SEIRstoc01N::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRstoc01N::get_time, "Get current time")
	  .property("trans_external", &SEIRstoc01N::get_trans_external, &SEIRstoc01N::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRstoc01N::get_trans_type, &SEIRstoc01N::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRstoc010 = SEIRmodel<update_type::stochastic,0,1,0,true>;
	class_<SEIRstoc010>("SEIRstoc010")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRstoc010::show, "The show/print method")
	  .method("update", &SEIRstoc010::update, "The update method")  
	  .method("run", &SEIRstoc010::run, "The run method")  
	  .method("save", &SEIRstoc010::save, "The save method")  
	  .method("reset", &SEIRstoc010::reset, "The reset method")  
	    
		.property("state", &SEIRstoc010::get_state, "Get current state")
	  .property("S", &SEIRstoc010::get_S, &SEIRstoc010::set_S, "Get/set current S")
	  .property("E", &SEIRstoc010::get_E, &SEIRstoc010::set_E, "Get/set current E")
	  .property("I", &SEIRstoc010::get_I, &SEIRstoc010::set_I, "Get/set current I")
	  .property("R", &SEIRstoc010::get_R, &SEIRstoc010::set_R, "Get/set current R")
	  .property("N", &SEIRstoc010::get_N, "Get current N")
	  .property("beta", &SEIRstoc010::get_beta, &SEIRstoc010::set_beta, "Get/set current beta")
	  .property("omega", &SEIRstoc010::get_omega, &SEIRstoc010::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRstoc010::get_gamma, &SEIRstoc010::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRstoc010::get_delta, &SEIRstoc010::set_delta, "Get/set current delta")
	  .property("repl", &SEIRstoc010::get_repl, &SEIRstoc010::set_repl, "Get/set current repl")
	  .property("cull", &SEIRstoc010::get_cull, &SEIRstoc010::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRstoc010::get_vacc, &SEIRstoc010::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRstoc010::get_time, "Get current time")
	  .property("trans_external", &SEIRstoc010::get_trans_external, &SEIRstoc010::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRstoc010::get_trans_type, &SEIRstoc010::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRstoc011 = SEIRmodel<update_type::stochastic,0,1,1,true>;
	class_<SEIRstoc011>("SEIRstoc011")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRstoc011::show, "The show/print method")
	  .method("update", &SEIRstoc011::update, "The update method")  
	  .method("run", &SEIRstoc011::run, "The run method")  
	  .method("save", &SEIRstoc011::save, "The save method")  
	  .method("reset", &SEIRstoc011::reset, "The reset method")  
	    
		.property("state", &SEIRstoc011::get_state, "Get current state")
	  .property("S", &SEIRstoc011::get_S, &SEIRstoc011::set_S, "Get/set current S")
	  .property("E", &SEIRstoc011::get_E, &SEIRstoc011::set_E, "Get/set current E")
	  .property("I", &SEIRstoc011::get_I, &SEIRstoc011::set_I, "Get/set current I")
	  .property("R", &SEIRstoc011::get_R, &SEIRstoc011::set_R, "Get/set current R")
	  .property("N", &SEIRstoc011::get_N, "Get current N")
	  .property("beta", &SEIRstoc011::get_beta, &SEIRstoc011::set_beta, "Get/set current beta")
	  .property("omega", &SEIRstoc011::get_omega, &SEIRstoc011::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRstoc011::get_gamma, &SEIRstoc011::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRstoc011::get_delta, &SEIRstoc011::set_delta, "Get/set current delta")
	  .property("repl", &SEIRstoc011::get_repl, &SEIRstoc011::set_repl, "Get/set current repl")
	  .property("cull", &SEIRstoc011::get_cull, &SEIRstoc011::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRstoc011::get_vacc, &SEIRstoc011::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRstoc011::get_time, "Get current time")
	  .property("trans_external", &SEIRstoc011::get_trans_external, &SEIRstoc011::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRstoc011::get_trans_type, &SEIRstoc011::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRstoc1NN = SEIRmodel<update_type::stochastic,1,-1,-1,true>;
	class_<SEIRstoc1NN>("SEIRstoc1NN")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRstoc1NN::show, "The show/print method")
	  .method("update", &SEIRstoc1NN::update, "The update method")  
	  .method("run", &SEIRstoc1NN::run, "The run method")  
	  .method("save", &SEIRstoc1NN::save, "The save method")  
	  .method("reset", &SEIRstoc1NN::reset, "The reset method")  
	    
		.property("state", &SEIRstoc1NN::get_state, "Get current state")
	  .property("S", &SEIRstoc1NN::get_S, &SEIRstoc1NN::set_S, "Get/set current S")
	  .property("E", &SEIRstoc1NN::get_E, &SEIRstoc1NN::set_E, "Get/set current E")
	  .property("I", &SEIRstoc1NN::get_I, &SEIRstoc1NN::set_I, "Get/set current I")
	  .property("R", &SEIRstoc1NN::get_R, &SEIRstoc1NN::set_R, "Get/set current R")
	  .property("N", &SEIRstoc1NN::get_N, "Get current N")
	  .property("beta", &SEIRstoc1NN::get_beta, &SEIRstoc1NN::set_beta, "Get/set current beta")
	  .property("omega", &SEIRstoc1NN::get_omega, &SEIRstoc1NN::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRstoc1NN::get_gamma, &SEIRstoc1NN::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRstoc1NN::get_delta, &SEIRstoc1NN::set_delta, "Get/set current delta")
	  .property("repl", &SEIRstoc1NN::get_repl, &SEIRstoc1NN::set_repl, "Get/set current repl")
	  .property("cull", &SEIRstoc1NN::get_cull, &SEIRstoc1NN::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRstoc1NN::get_vacc, &SEIRstoc1NN::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRstoc1NN::get_time, "Get current time")
	  .property("trans_external", &SEIRstoc1NN::get_trans_external, &SEIRstoc1NN::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRstoc1NN::get_trans_type, &SEIRstoc1NN::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRstoc1N0 = SEIRmodel<update_type::stochastic,1,-1,0,true>;
	class_<SEIRstoc1N0>("SEIRstoc1N0")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRstoc1N0::show, "The show/print method")
	  .method("update", &SEIRstoc1N0::update, "The update method")  
	  .method("run", &SEIRstoc1N0::run, "The run method")  
	  .method("save", &SEIRstoc1N0::save, "The save method")  
	  .method("reset", &SEIRstoc1N0::reset, "The reset method")  
	    
		.property("state", &SEIRstoc1N0::get_state, "Get current state")
	  .property("S", &SEIRstoc1N0::get_S, &SEIRstoc1N0::set_S, "Get/set current S")
	  .property("E", &SEIRstoc1N0::get_E, &SEIRstoc1N0::set_E, "Get/set current E")
	  .property("I", &SEIRstoc1N0::get_I, &SEIRstoc1N0::set_I, "Get/set current I")
	  .property("R", &SEIRstoc1N0::get_R, &SEIRstoc1N0::set_R, "Get/set current R")
	  .property("N", &SEIRstoc1N0::get_N, "Get current N")
	  .property("beta", &SEIRstoc1N0::get_beta, &SEIRstoc1N0::set_beta, "Get/set current beta")
	  .property("omega", &SEIRstoc1N0::get_omega, &SEIRstoc1N0::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRstoc1N0::get_gamma, &SEIRstoc1N0::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRstoc1N0::get_delta, &SEIRstoc1N0::set_delta, "Get/set current delta")
	  .property("repl", &SEIRstoc1N0::get_repl, &SEIRstoc1N0::set_repl, "Get/set current repl")
	  .property("cull", &SEIRstoc1N0::get_cull, &SEIRstoc1N0::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRstoc1N0::get_vacc, &SEIRstoc1N0::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRstoc1N0::get_time, "Get current time")
	  .property("trans_external", &SEIRstoc1N0::get_trans_external, &SEIRstoc1N0::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRstoc1N0::get_trans_type, &SEIRstoc1N0::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRstoc1N1 = SEIRmodel<update_type::stochastic,1,-1,1,true>;
	class_<SEIRstoc1N1>("SEIRstoc1N1")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRstoc1N1::show, "The show/print method")
	  .method("update", &SEIRstoc1N1::update, "The update method")  
	  .method("run", &SEIRstoc1N1::run, "The run method")  
	  .method("save", &SEIRstoc1N1::save, "The save method")  
	  .method("reset", &SEIRstoc1N1::reset, "The reset method")  
	    
		.property("state", &SEIRstoc1N1::get_state, "Get current state")
	  .property("S", &SEIRstoc1N1::get_S, &SEIRstoc1N1::set_S, "Get/set current S")
	  .property("E", &SEIRstoc1N1::get_E, &SEIRstoc1N1::set_E, "Get/set current E")
	  .property("I", &SEIRstoc1N1::get_I, &SEIRstoc1N1::set_I, "Get/set current I")
	  .property("R", &SEIRstoc1N1::get_R, &SEIRstoc1N1::set_R, "Get/set current R")
	  .property("N", &SEIRstoc1N1::get_N, "Get current N")
	  .property("beta", &SEIRstoc1N1::get_beta, &SEIRstoc1N1::set_beta, "Get/set current beta")
	  .property("omega", &SEIRstoc1N1::get_omega, &SEIRstoc1N1::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRstoc1N1::get_gamma, &SEIRstoc1N1::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRstoc1N1::get_delta, &SEIRstoc1N1::set_delta, "Get/set current delta")
	  .property("repl", &SEIRstoc1N1::get_repl, &SEIRstoc1N1::set_repl, "Get/set current repl")
	  .property("cull", &SEIRstoc1N1::get_cull, &SEIRstoc1N1::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRstoc1N1::get_vacc, &SEIRstoc1N1::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRstoc1N1::get_time, "Get current time")
	  .property("trans_external", &SEIRstoc1N1::get_trans_external, &SEIRstoc1N1::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRstoc1N1::get_trans_type, &SEIRstoc1N1::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRstoc11N = SEIRmodel<update_type::stochastic,1,1,-1,true>;
	class_<SEIRstoc11N>("SEIRstoc11N")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRstoc11N::show, "The show/print method")
	  .method("update", &SEIRstoc11N::update, "The update method")  
	  .method("run", &SEIRstoc11N::run, "The run method")  
	  .method("save", &SEIRstoc11N::save, "The save method")  
	  .method("reset", &SEIRstoc11N::reset, "The reset method")  
	    
		.property("state", &SEIRstoc11N::get_state, "Get current state")
	  .property("S", &SEIRstoc11N::get_S, &SEIRstoc11N::set_S, "Get/set current S")
	  .property("E", &SEIRstoc11N::get_E, &SEIRstoc11N::set_E, "Get/set current E")
	  .property("I", &SEIRstoc11N::get_I, &SEIRstoc11N::set_I, "Get/set current I")
	  .property("R", &SEIRstoc11N::get_R, &SEIRstoc11N::set_R, "Get/set current R")
	  .property("N", &SEIRstoc11N::get_N, "Get current N")
	  .property("beta", &SEIRstoc11N::get_beta, &SEIRstoc11N::set_beta, "Get/set current beta")
	  .property("omega", &SEIRstoc11N::get_omega, &SEIRstoc11N::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRstoc11N::get_gamma, &SEIRstoc11N::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRstoc11N::get_delta, &SEIRstoc11N::set_delta, "Get/set current delta")
	  .property("repl", &SEIRstoc11N::get_repl, &SEIRstoc11N::set_repl, "Get/set current repl")
	  .property("cull", &SEIRstoc11N::get_cull, &SEIRstoc11N::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRstoc11N::get_vacc, &SEIRstoc11N::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRstoc11N::get_time, "Get current time")
	  .property("trans_external", &SEIRstoc11N::get_trans_external, &SEIRstoc11N::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRstoc11N::get_trans_type, &SEIRstoc11N::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRstoc110 = SEIRmodel<update_type::stochastic,1,1,0,true>;
	class_<SEIRstoc110>("SEIRstoc110")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRstoc110::show, "The show/print method")
	  .method("update", &SEIRstoc110::update, "The update method")  
	  .method("run", &SEIRstoc110::run, "The run method")  
	  .method("save", &SEIRstoc110::save, "The save method")  
	  .method("reset", &SEIRstoc110::reset, "The reset method")  
	    
		.property("state", &SEIRstoc110::get_state, "Get current state")
	  .property("S", &SEIRstoc110::get_S, &SEIRstoc110::set_S, "Get/set current S")
	  .property("E", &SEIRstoc110::get_E, &SEIRstoc110::set_E, "Get/set current E")
	  .property("I", &SEIRstoc110::get_I, &SEIRstoc110::set_I, "Get/set current I")
	  .property("R", &SEIRstoc110::get_R, &SEIRstoc110::set_R, "Get/set current R")
	  .property("N", &SEIRstoc110::get_N, "Get current N")
	  .property("beta", &SEIRstoc110::get_beta, &SEIRstoc110::set_beta, "Get/set current beta")
	  .property("omega", &SEIRstoc110::get_omega, &SEIRstoc110::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRstoc110::get_gamma, &SEIRstoc110::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRstoc110::get_delta, &SEIRstoc110::set_delta, "Get/set current delta")
	  .property("repl", &SEIRstoc110::get_repl, &SEIRstoc110::set_repl, "Get/set current repl")
	  .property("cull", &SEIRstoc110::get_cull, &SEIRstoc110::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRstoc110::get_vacc, &SEIRstoc110::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRstoc110::get_time, "Get current time")
	  .property("trans_external", &SEIRstoc110::get_trans_external, &SEIRstoc110::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRstoc110::get_trans_type, &SEIRstoc110::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRstoc111 = SEIRmodel<update_type::stochastic,1,1,1,true>;
	class_<SEIRstoc111>("SEIRstoc111")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRstoc111::show, "The show/print method")
	  .method("update", &SEIRstoc111::update, "The update method")  
	  .method("run", &SEIRstoc111::run, "The run method")  
	  .method("save", &SEIRstoc111::save, "The save method")  
	  .method("reset", &SEIRstoc111::reset, "The reset method")  
	    
		.property("state", &SEIRstoc111::get_state, "Get current state")
	  .property("S", &SEIRstoc111::get_S, &SEIRstoc111::set_S, "Get/set current S")
	  .property("E", &SEIRstoc111::get_E, &SEIRstoc111::set_E, "Get/set current E")
	  .property("I", &SEIRstoc111::get_I, &SEIRstoc111::set_I, "Get/set current I")
	  .property("R", &SEIRstoc111::get_R, &SEIRstoc111::set_R, "Get/set current R")
	  .property("N", &SEIRstoc111::get_N, "Get current N")
	  .property("beta", &SEIRstoc111::get_beta, &SEIRstoc111::set_beta, "Get/set current beta")
	  .property("omega", &SEIRstoc111::get_omega, &SEIRstoc111::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRstoc111::get_gamma, &SEIRstoc111::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRstoc111::get_delta, &SEIRstoc111::set_delta, "Get/set current delta")
	  .property("repl", &SEIRstoc111::get_repl, &SEIRstoc111::set_repl, "Get/set current repl")
	  .property("cull", &SEIRstoc111::get_cull, &SEIRstoc111::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRstoc111::get_vacc, &SEIRstoc111::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRstoc111::get_time, "Get current time")
	  .property("trans_external", &SEIRstoc111::get_trans_external, &SEIRstoc111::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRstoc111::get_trans_type, &SEIRstoc111::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRstoc3NN = SEIRmodel<update_type::stochastic,3,-1,-1,true>;
	class_<SEIRstoc3NN>("SEIRstoc3NN")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRstoc3NN::show, "The show/print method")
	  .method("update", &SEIRstoc3NN::update, "The update method")  
	  .method("run", &SEIRstoc3NN::run, "The run method")  
	  .method("save", &SEIRstoc3NN::save, "The save method")  
	  .method("reset", &SEIRstoc3NN::reset, "The reset method")  
	    
		.property("state", &SEIRstoc3NN::get_state, "Get current state")
	  .property("S", &SEIRstoc3NN::get_S, &SEIRstoc3NN::set_S, "Get/set current S")
	  .property("E", &SEIRstoc3NN::get_E, &SEIRstoc3NN::set_E, "Get/set current E")
	  .property("I", &SEIRstoc3NN::get_I, &SEIRstoc3NN::set_I, "Get/set current I")
	  .property("R", &SEIRstoc3NN::get_R, &SEIRstoc3NN::set_R, "Get/set current R")
	  .property("N", &SEIRstoc3NN::get_N, "Get current N")
	  .property("beta", &SEIRstoc3NN::get_beta, &SEIRstoc3NN::set_beta, "Get/set current beta")
	  .property("omega", &SEIRstoc3NN::get_omega, &SEIRstoc3NN::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRstoc3NN::get_gamma, &SEIRstoc3NN::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRstoc3NN::get_delta, &SEIRstoc3NN::set_delta, "Get/set current delta")
	  .property("repl", &SEIRstoc3NN::get_repl, &SEIRstoc3NN::set_repl, "Get/set current repl")
	  .property("cull", &SEIRstoc3NN::get_cull, &SEIRstoc3NN::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRstoc3NN::get_vacc, &SEIRstoc3NN::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRstoc3NN::get_time, "Get current time")
	  .property("trans_external", &SEIRstoc3NN::get_trans_external, &SEIRstoc3NN::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRstoc3NN::get_trans_type, &SEIRstoc3NN::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRstoc3N0 = SEIRmodel<update_type::stochastic,3,-1,0,true>;
	class_<SEIRstoc3N0>("SEIRstoc3N0")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRstoc3N0::show, "The show/print method")
	  .method("update", &SEIRstoc3N0::update, "The update method")  
	  .method("run", &SEIRstoc3N0::run, "The run method")  
	  .method("save", &SEIRstoc3N0::save, "The save method")  
	  .method("reset", &SEIRstoc3N0::reset, "The reset method")  
	    
		.property("state", &SEIRstoc3N0::get_state, "Get current state")
	  .property("S", &SEIRstoc3N0::get_S, &SEIRstoc3N0::set_S, "Get/set current S")
	  .property("E", &SEIRstoc3N0::get_E, &SEIRstoc3N0::set_E, "Get/set current E")
	  .property("I", &SEIRstoc3N0::get_I, &SEIRstoc3N0::set_I, "Get/set current I")
	  .property("R", &SEIRstoc3N0::get_R, &SEIRstoc3N0::set_R, "Get/set current R")
	  .property("N", &SEIRstoc3N0::get_N, "Get current N")
	  .property("beta", &SEIRstoc3N0::get_beta, &SEIRstoc3N0::set_beta, "Get/set current beta")
	  .property("omega", &SEIRstoc3N0::get_omega, &SEIRstoc3N0::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRstoc3N0::get_gamma, &SEIRstoc3N0::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRstoc3N0::get_delta, &SEIRstoc3N0::set_delta, "Get/set current delta")
	  .property("repl", &SEIRstoc3N0::get_repl, &SEIRstoc3N0::set_repl, "Get/set current repl")
	  .property("cull", &SEIRstoc3N0::get_cull, &SEIRstoc3N0::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRstoc3N0::get_vacc, &SEIRstoc3N0::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRstoc3N0::get_time, "Get current time")
	  .property("trans_external", &SEIRstoc3N0::get_trans_external, &SEIRstoc3N0::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRstoc3N0::get_trans_type, &SEIRstoc3N0::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRstoc3N1 = SEIRmodel<update_type::stochastic,3,-1,1,true>;
	class_<SEIRstoc3N1>("SEIRstoc3N1")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRstoc3N1::show, "The show/print method")
	  .method("update", &SEIRstoc3N1::update, "The update method")  
	  .method("run", &SEIRstoc3N1::run, "The run method")  
	  .method("save", &SEIRstoc3N1::save, "The save method")  
	  .method("reset", &SEIRstoc3N1::reset, "The reset method")  
	    
		.property("state", &SEIRstoc3N1::get_state, "Get current state")
	  .property("S", &SEIRstoc3N1::get_S, &SEIRstoc3N1::set_S, "Get/set current S")
	  .property("E", &SEIRstoc3N1::get_E, &SEIRstoc3N1::set_E, "Get/set current E")
	  .property("I", &SEIRstoc3N1::get_I, &SEIRstoc3N1::set_I, "Get/set current I")
	  .property("R", &SEIRstoc3N1::get_R, &SEIRstoc3N1::set_R, "Get/set current R")
	  .property("N", &SEIRstoc3N1::get_N, "Get current N")
	  .property("beta", &SEIRstoc3N1::get_beta, &SEIRstoc3N1::set_beta, "Get/set current beta")
	  .property("omega", &SEIRstoc3N1::get_omega, &SEIRstoc3N1::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRstoc3N1::get_gamma, &SEIRstoc3N1::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRstoc3N1::get_delta, &SEIRstoc3N1::set_delta, "Get/set current delta")
	  .property("repl", &SEIRstoc3N1::get_repl, &SEIRstoc3N1::set_repl, "Get/set current repl")
	  .property("cull", &SEIRstoc3N1::get_cull, &SEIRstoc3N1::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRstoc3N1::get_vacc, &SEIRstoc3N1::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRstoc3N1::get_time, "Get current time")
	  .property("trans_external", &SEIRstoc3N1::get_trans_external, &SEIRstoc3N1::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRstoc3N1::get_trans_type, &SEIRstoc3N1::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRstoc31N = SEIRmodel<update_type::stochastic,3,1,-1,true>;
	class_<SEIRstoc31N>("SEIRstoc31N")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRstoc31N::show, "The show/print method")
	  .method("update", &SEIRstoc31N::update, "The update method")  
	  .method("run", &SEIRstoc31N::run, "The run method")  
	  .method("save", &SEIRstoc31N::save, "The save method")  
	  .method("reset", &SEIRstoc31N::reset, "The reset method")  
	    
		.property("state", &SEIRstoc31N::get_state, "Get current state")
	  .property("S", &SEIRstoc31N::get_S, &SEIRstoc31N::set_S, "Get/set current S")
	  .property("E", &SEIRstoc31N::get_E, &SEIRstoc31N::set_E, "Get/set current E")
	  .property("I", &SEIRstoc31N::get_I, &SEIRstoc31N::set_I, "Get/set current I")
	  .property("R", &SEIRstoc31N::get_R, &SEIRstoc31N::set_R, "Get/set current R")
	  .property("N", &SEIRstoc31N::get_N, "Get current N")
	  .property("beta", &SEIRstoc31N::get_beta, &SEIRstoc31N::set_beta, "Get/set current beta")
	  .property("omega", &SEIRstoc31N::get_omega, &SEIRstoc31N::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRstoc31N::get_gamma, &SEIRstoc31N::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRstoc31N::get_delta, &SEIRstoc31N::set_delta, "Get/set current delta")
	  .property("repl", &SEIRstoc31N::get_repl, &SEIRstoc31N::set_repl, "Get/set current repl")
	  .property("cull", &SEIRstoc31N::get_cull, &SEIRstoc31N::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRstoc31N::get_vacc, &SEIRstoc31N::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRstoc31N::get_time, "Get current time")
	  .property("trans_external", &SEIRstoc31N::get_trans_external, &SEIRstoc31N::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRstoc31N::get_trans_type, &SEIRstoc31N::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRstoc310 = SEIRmodel<update_type::stochastic,3,1,0,true>;
	class_<SEIRstoc310>("SEIRstoc310")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRstoc310::show, "The show/print method")
	  .method("update", &SEIRstoc310::update, "The update method")  
	  .method("run", &SEIRstoc310::run, "The run method")  
	  .method("save", &SEIRstoc310::save, "The save method")  
	  .method("reset", &SEIRstoc310::reset, "The reset method")  
	    
		.property("state", &SEIRstoc310::get_state, "Get current state")
	  .property("S", &SEIRstoc310::get_S, &SEIRstoc310::set_S, "Get/set current S")
	  .property("E", &SEIRstoc310::get_E, &SEIRstoc310::set_E, "Get/set current E")
	  .property("I", &SEIRstoc310::get_I, &SEIRstoc310::set_I, "Get/set current I")
	  .property("R", &SEIRstoc310::get_R, &SEIRstoc310::set_R, "Get/set current R")
	  .property("N", &SEIRstoc310::get_N, "Get current N")
	  .property("beta", &SEIRstoc310::get_beta, &SEIRstoc310::set_beta, "Get/set current beta")
	  .property("omega", &SEIRstoc310::get_omega, &SEIRstoc310::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRstoc310::get_gamma, &SEIRstoc310::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRstoc310::get_delta, &SEIRstoc310::set_delta, "Get/set current delta")
	  .property("repl", &SEIRstoc310::get_repl, &SEIRstoc310::set_repl, "Get/set current repl")
	  .property("cull", &SEIRstoc310::get_cull, &SEIRstoc310::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRstoc310::get_vacc, &SEIRstoc310::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRstoc310::get_time, "Get current time")
	  .property("trans_external", &SEIRstoc310::get_trans_external, &SEIRstoc310::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRstoc310::get_trans_type, &SEIRstoc310::set_trans_type, "Get/set current trans_type")
	; 

	using SEIRstoc311 = SEIRmodel<update_type::stochastic,3,1,1,true>;
	class_<SEIRstoc311>("SEIRstoc311")
	  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
	  .factory(invalidate_default_constructor)
	    
		.method("show", &SEIRstoc311::show, "The show/print method")
	  .method("update", &SEIRstoc311::update, "The update method")  
	  .method("run", &SEIRstoc311::run, "The run method")  
	  .method("save", &SEIRstoc311::save, "The save method")  
	  .method("reset", &SEIRstoc311::reset, "The reset method")  
	    
		.property("state", &SEIRstoc311::get_state, "Get current state")
	  .property("S", &SEIRstoc311::get_S, &SEIRstoc311::set_S, "Get/set current S")
	  .property("E", &SEIRstoc311::get_E, &SEIRstoc311::set_E, "Get/set current E")
	  .property("I", &SEIRstoc311::get_I, &SEIRstoc311::set_I, "Get/set current I")
	  .property("R", &SEIRstoc311::get_R, &SEIRstoc311::set_R, "Get/set current R")
	  .property("N", &SEIRstoc311::get_N, "Get current N")
	  .property("beta", &SEIRstoc311::get_beta, &SEIRstoc311::set_beta, "Get/set current beta")
	  .property("omega", &SEIRstoc311::get_omega, &SEIRstoc311::set_omega, "Get/set current omega")
	  .property("gamma", &SEIRstoc311::get_gamma, &SEIRstoc311::set_gamma, "Get/set current gamma")
	  .property("delta", &SEIRstoc311::get_delta, &SEIRstoc311::set_delta, "Get/set current delta")
	  .property("repl", &SEIRstoc311::get_repl, &SEIRstoc311::set_repl, "Get/set current repl")
	  .property("cull", &SEIRstoc311::get_cull, &SEIRstoc311::set_cull, "Get/set current cull")
	  .property("vacc", &SEIRstoc311::get_vacc, &SEIRstoc311::set_vacc, "Get/set current vacc")
	  .property("time", &SEIRstoc311::get_time, "Get current time")
	  .property("trans_external", &SEIRstoc311::get_trans_external, &SEIRstoc311::set_trans_external, "Get/set current trans_external")
	  .property("transmission_type", &SEIRstoc311::get_trans_type, &SEIRstoc311::set_trans_type, "Get/set current trans_type")
	; 


}

/*

  DO NOT MODIFY THIS FILE DIRECTLY!
  See module/ipdmr_module_template.cpp

*/ 

