class_<NAME>("NAME")
  .constructor<const int, const int, const int, const Rcpp::CharacterVector>("Constructor")
  .factory(invalidate_default_constructor)
    
	.method("show", &NAME::show, "The show/print method")
  .method("update", &NAME::update, "The update method")  
  .method("run", &NAME::run, "The run method")  
  .method("save", &NAME::save, "The save method")  
  .method("reset", &NAME::reset, "The reset method")  
    
	.property("state", &NAME::get_state, "Get current state")
  .property("S", &NAME::get_S, &NAME::set_S, "Get/set current S")
  .property("E", &NAME::get_E, &NAME::set_E, "Get/set current E")
  .property("I", &NAME::get_I, &NAME::set_I, "Get/set current I")
  .property("R", &NAME::get_R, &NAME::set_R, "Get/set current R")
  .property("N", &NAME::get_N, "Get current N")
  .property("beta", &NAME::get_beta, &NAME::set_beta, "Get/set current beta")
  .property("omega", &NAME::get_omega, &NAME::set_omega, "Get/set current omega")
  .property("gamma", &NAME::get_gamma, &NAME::set_gamma, "Get/set current gamma")
  .property("delta", &NAME::get_delta, &NAME::set_delta, "Get/set current delta")
  .property("repl", &NAME::get_repl, &NAME::set_repl, "Get/set current repl")
  .property("cull", &NAME::get_cull, &NAME::set_cull, "Get/set current cull")
  .property("vacc", &NAME::get_vacc, &NAME::set_vacc, "Get/set current vacc")
  .property("time", &NAME::get_time, "Get current time")
  .property("trans_external", &NAME::get_trans_external, &NAME::set_trans_external, "Get/set current trans_external")
  .property("transmission_type", &NAME::get_trans_type, &NAME::set_trans_type, "Get/set current trans_type")
;
